[package]
name = "pricing-engine"
version = "0.1.0"
authors = ["Cameron Pfiffer <cpfiffer@gmail.com>"]

[dependencies]
rand = "0.5"
log = "0.4"
pretty_env_logger = "0.2.4"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"

